### ISSUE TITLE
cognitoUser.authenticateUser is not working

### ISSUE THREAD

**Issue by zhaoyi0113** [aws/amazon-cognito-identity-js#586]
I am using below code to authenticate an user. 

```
let authenticationData = {
        Username : email,
        Password : password,
    };
    let authenticationDetails = new AuthenticationDetails(authenticationData);
    let userData = {
        Username : email,
        Pool : userPool
    };
    let cognitoUser = new CognitoUser(userData);
    console.log('cognitoUser=',cognitoUser);
    cognitoUser.authenticateUser(authenticationDetails, {
        onSuccess: function (result) {
            console.log('result=', result);
            console.log('access token + ' + result.getAccessToken().getJwtToken());

        },
        onFailure: function(err) {
            alert(err);
        },
    });
```

I will get an error if the user doesn't exist or users not confirmed. This is expected behaviour. But if I login with a correct user name and password. I will get below exceptions.

```
request.js?1405:31 Uncaught Error: callback is not a function
    at eval (eval at <anonymous> (main.bundle.js:2994), <anonymous>:167:7)
    at BigInteger.bnModPow [as modPow] (eval at <anonymous> (main.bundle.js:3006), <anonymous>:764:3)
    at AuthenticationHelper.generateHashDevice (eval at <anonymous> (main.bundle.js:2994), <anonymous>:161:12)
    at CognitoUser.authenticateUserInternal (eval at <anonymous> (main.bundle.js:3036),
```

**Comment by dzmitry-kankalovich** [comment]
Same issue here, appeared right after update to 1.23.0

**Comment by itrestian** [comment]
Is this react native only, similar to the issue below? Also if you disable device tracking in the console will it work?

https://github.com/aws/amazon-cognito-identity-js/issues/585

**Comment by jonstokes** [comment]
Same here. I actually got it to quit failing by modifying line 396 of `lib/CognitoUser.js` as follows:

` authenticationHelper.generateHashDevice(dataAuthenticate.AuthenticationResult.NewDeviceMetadata.DeviceGroupKey, dataAuthenticate.AuthenticationResult.NewDeviceMetadata.DeviceKey, function() { console.log('Win!!') });`

In other words, this line is calling `generateHashDevice` without that third `callback` argument, which is causing the whole thing to blow up. Or at least, as near as I can tell that's what it is. I have some other issues after this (probably because I'm a cognito n00b and am trying to do something impossible), but at least the code runs.

Edit: Also, this is not even on react. I'm just feeling my way around the code with this little tool right here, and it blows up: https://github.com/AnomalyInnovations/aws-api-gateway-cli-test

**Comment by itrestian** [comment]
Pull request was merged.

**Comment by jonstokes** [comment]
Awesome, thanks!
