### ISSUE TITLE
 AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool is not a function

### ISSUE THREAD

**Issue by jagadeeshmarthy** [aws/amazon-cognito-identity-js#392]
Getting  AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool is not a function. It was working fine from past 4 months. I don't know why I'm suddenly getting this error while deploying my node js code to ec2 and when I'm trying to signin using cognito from my local I'm able to do it. I'm using aws-sdk-2.5.3. 
It would be great if someone can help me who has got similar issue as this is happening for my production server and I'm stuck.

Thanks in Advance.

**Comment by alexanderbh** [comment]
Install 1.16.0 again. Something is wrong with 1.17.0 it seems. It does not work for me either.

**Comment by jagadeeshmarthy** [comment]
Still getting the error even after using 1.16.0, but I was using 1.10.0 previously.
I'm using the following versions aws-sdk -2.5.3 aws-cognito-identity-js:1.10.0.

**Comment by jagadeeshmarthy** [comment]
okay, got it. Thank you @alexanderbh.

**Comment by forforf** [comment]
I think I've got this working for me, not sure if it will help anyone else or not.

This worked in v1.16.0 but broke in v1.17.0
```
import AWS from "aws-sdk";
import {CognitoUserPool} from "amazon-cognito-identity-js";

// later in a callback - broke in v1.17.0
const userPool = new AWS.CognitoIdentityServiceProvider.CognitoUserPool(poolData);
```

This worked in v1.17.0
```
import AWS from "aws-sdk";
import {CognitoUserPool} from "amazon-cognito-identity-js";

// later in a callback - works in v1.17.0
const userPool = new CognitoUserPool(poolData);
```

**Comment by MichaelCPell** [comment]
This may depend on the way you are requiring and referencing the AWS-SDK vs (this) Cognito SDK.  @forforf's solution works with the 1.17.0+ Type Definition file installed.
