### ISSUE TITLE
Property 'CognitoUserPool' does not exist on type 'typeof CognitoIdentityServiceProvider'.

### ISSUE THREAD

**Issue by bennypowers** [aws/amazon-cognito-identity-js#559]
When importing amazon-cognito-identity-js@1.21.0 into a typescript file in my project, I receive the following error:

```ts
import * as AWSCognito from 'amazon-cognito-identity-js'
// ... 
const userPool: CognitoUserPool = new AWSCognito
  .CognitoIdentityServiceProvider.CognitoUserPool(poolData);
```

```
Property 'CognitoUserPool' does not exist on type 'typeof CognitoIdentityServiceProvider'.
```

**Comment by bennypowers** [comment]
See also https://github.com/aws/amazon-cognito-identity-js/issues/392

**Comment by yuntuowang** [comment]
This worked in v1.16.0 but broke in v1.17.0

import AWS from "aws-sdk";
import {CognitoUserPool} from "amazon-cognito-identity-js";

// later in a callback - broke in v1.17.0
const userPool = new AWS.CognitoIdentityServiceProvider.CognitoUserPool(poolData);
This worked in v1.17.0

import AWS from "aws-sdk";
import {CognitoUserPool} from "amazon-cognito-identity-js";

// later in a callback - works in v1.17.0
const userPool = new CognitoUserPool(poolData);
